config/routes.rb
Rails.application.routes.draw do
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path

  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path

  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end
end

private

def find_article
  @article = Article.find(params[:id])
end

def article_params
    params.require(:article).permit(:title, :content)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<h1>All articles</h1>

<%= link_to "+Add new article", new_article_path %>

<div class="container">
  <ul>
   <% @articles.each do |article| %>
      <li><%= link_to article.title, article_path(article)%></li>
    <% end %>
  </ul>
</div>

app/views/articles/new.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%=@article.content%></p>
<%= link_to "Delete #{@article.title}",
            article_path(@article),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>